server:
  port: 8081
  servlet:
     context-path: /menu
spring:
  application:
    name: menu-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'