server:
  port: 10001
spring:
  application:
    name: zuul-proxy

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:9999/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'     
